name: first Workflow
on: workflow_dispatch
jobs:
  first-job:
   runs-on: ubuntu-latest
   steps:
    - name: print greeting
      run: echo "Hello words"
    - name: print goodbye
      run: echo "done- bye!"
    - name: latest code 
      run: echo "done lasted changes"
      run: echo "my second change done lasted changes123"

