name: first Workflow
on: workflow_dispatch
jobs:
  first-job:
   runs-on: ubuntu-latest
   steps:
    - name: print greeting
      run: echo "Hello words"
    - name: print goodbye
      run: echo "done- bye!"
